name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add rustfmt
      run: rustup component add rustfmt
    - name:  Check formatting
      run: cargo fmt --check
    - name: Add clippy
      run: rustup component add clippy
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings    
    - name: Run tests
      run: cargo test --verbose
